---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: roller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: roller
    spec:
      restartPolicy: Always

      containers:
        - name: roller
          image: eu.gcr.io/wire-bot/roller:latest

          resources:
            requests:
              memory: "50Mi"
            limits:
              memory: "500Mi"

          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: roller-knows
                  key: token

            - name: KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: roller-knows
                  key: keystore_password

          volumeMounts:
            - name: roller-disk
              mountPath: /var/lib/roller/crypto

            - name: roller-config
              mountPath: /etc/roller

          command:
            - "/usr/bin/java"
            - "-Ddw.server.applicationConnectors[1].keyStorePassword=$(KEYSTORE_PASSWORD)"
            - "-Ddw.auth=$(TOKEN)"
            - "-Ddw.cryptoDir=/var/lib/roller/crypto"
            - "-jar"
            - "roller.jar"
            - "server"
            - "/etc/roller/roller.yaml"

      volumes:
        - name: roller-disk
          gcePersistentDisk:
            pdName: roller-disk
            fsType: ext4

        - name: roller-config
          configMap:
            name: roller-config

---
apiVersion: v1
kind: Service
metadata:
  name: roller
spec:
  selector:
    name: roller
  type: LoadBalancer
  ports:
    - name: https
      port: 443
      targetPort: 4443
      protocol: TCP